# Generated by Django 3.1.1 on 2020-10-04 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_type', models.CharField(max_length=50)),
                ('serial_number', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_type', models.CharField(max_length=50)),
                ('mask_serial_number', models.CharField(max_length=10)),
            ],
        ),
    ]
