# Generated by Django 3.1.1 on 2020-10-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20201004_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='serial_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
